<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SALARIOS</h1>
    <h2>FORMULARIO DE CAPTURA</h2>
    <Br>
    <p></p>
    <form action="2_FORMULARIO_EMPLEADO.PHP"method="get">
        <label>Nombre del empleado: </label>
        <input type="txt" name="nombre_n1"><br>
        <label>cargo: </label>
        <input type="txt" name="cargo_c1"><br>
        <label>salario: </label>
        <input type="number" name="salar_s1"><br>


    <input type="submit" name="btn_enviar" value="ejecutar">
</body>
</html>