<?php
$vrnumero1 = 150;
$vrnumero2= 150;

$vrrespuesta = $num1 + $num2;

 echo "la suma es: ".$vrrespuesta; "<br />";



 $num1 = 200;
 $num2 = 120;

 $resultado = $num1- $num2; 
 echo "la resta es: ".$resultado; "<br />";

 $num1 = 5;
 $num2 = 8; 

 $resultado = $num1 * $num2;
 echo "la multiplicacion es: ".$resultado; "<br />";


 $num1 = 20;
 $num2 = 2;

 $resultado = $num1 / $num2;
 echo "la division es: ".$resultado; "<br />";






























?>